#!/bin/bash
# Poor me, I don't know how to do Linux.
# Waaaaaaah.
# But at least I'm good at commenting!
# Will the teacher ever stop teasing me??

echo "This isn't the right output at all!"
echo "Maybe if your grading script isn't very good,"
echo "I'll get away with it."
echo 
echo "If I help out with Ruby and Python,"
echo "Maybe they will let me stick around."
echo
echo "Possibly."
echo
echo "One of these days I really should learn Java."
echo
echo "But it is so tough!"
echo "I wish it were easy and wonderful to program in like bash is."
echo
echo "Would they let me re-take 143 while TAing it?"
echo "Hmm..."
echo
